### PR TITLE
CI: Removed Ubuntu 18.04 build.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**

### CODE REVIEW

**Comment by robbat2** [comment]
Please also update Dockerfile.autogen

**Review by robbat2 — CHANGES_REQUESTED** [review]
1. remove the `ciao` file
2. fix the other reference in Dockerfile

**Comment by RICCIARDI-Adrien** [comment]
Sorry for forgetting the `ciao` file !
Is it OK now ?

**Comment by RICCIARDI-Adrien** [comment]
@robbat2 After this PR and the FreeBSD one are accepted I have other PR to fully fix the CI.

**Review by robbat2 — APPROVED** [review]

**Pull request merged**
