### PR TITLE
ci: Added Ubuntu 24.04.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**

### CODE REVIEW

**Comment by RICCIARDI-Adrien** [comment]
Can someone with enough permissions restart the Linux workflow ? The error is due to a failed connection while downloading a package...
Thanks !

**Comment by stappersg** [comment]
On Thu, Dec 05, 2024 at 02:37:37PM -0800, Adrien RICCIARDI wrote:
> Can someone with enough permissions restart the Linux workflow ?

Done

**Review by stappersg — APPROVED** [review]
All good

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Thanks!

**Pull request merged**
