### PR TITLE
send: refactor prefix lifetime limiter

### PR DESCRIPTION
**Pull request by robbat2**
In PR#127, I suggested that the block of code to limit prefix lifetimes
be refactored and reused. In implementing that I wonder if we're
clobbering some stored prefix lifetimes in some cases and accidently
having a time-bomb behavior. PR needs strong review & testing.

Reference: https://github.com/radvd-project/radvd/pull/127#discussion_r606072523
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

### CODE REVIEW

**Comment by robbat2** [comment]
CC @samboyles1 I implemented the helper function, and now I really wonder about a subtle class of bugs in `radvd` where some data might be clobbered. Would appreciate review from you as well as others.

**Comment by samboyles1** [comment]
Thanks @robbat2, I will do some testing and review tomorrow the way I initially did my testing with #127

**Comment by samboyles1** [comment]
@robbat2 it looks as though the lifetimes are being sent as I had expected in #127 with your additional change. Would you be able to explain a bit more about what data you think might get clobbered, Is it the lifetime information from radvd.conf? Or do you have a specific case in mind that might cause the issues to occur?

**Comment by robbat2** [comment]
@stappersg does this look correct enough to you?

**Review by stappersg — APPROVED** [review]
Approved to get this project moving.

**Pull request merged**
