### PR TITLE
 Add the socket option IPV6_MULTICAST_LOOP

### PR DESCRIPTION
**Pull request by XWwalker**
#226

### CODE REVIEW

**Comment by XWwalker** [comment]
Add the socket option IPV6_MULTICAST_LOOP to prevent the interface from autoconfiguring using RA messages sent by itself.

**Comment by robbat2** [comment]
I'm going to merge this AFTER the current release; I don't want to introduce a change in behavior between RC and final release.

**Review by robbat2 — APPROVED** [review]

**Comment by jlyonsmith** [comment]
I think this is a pretty important bug fix.  When will it be release?

**Comment by reubenhwk** [comment]
Is there any reason this is not yet merged?

**Comment by stappersg** [comment]
> Is there any reason this is not yet merged?

https://github.com/radvd-project/radvd/pull/227#issuecomment-1869160237

**Pull request merged**
