### PR TITLE
radvd: save pwnam if no user or root is passed

### PR DESCRIPTION
**Pull request by robbat2**
If -u is not passed, or -u root is passed, the is-config-writable by own
uid or own gid check is not needed, so skip the pwnam that it causes.

Reference: https://github.com/radvd-project/radvd/issues/165
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

### CODE REVIEW

**Comment by stappersg** [comment]
Looks good to me.

Let's discuss _"need info on how this is being used badly with systemd"_ in #165

**Comment by robbat2** [comment]
@stappersg +1 anyway?

**Comment by robbat2** [comment]
@stappersg I think this is still valuable, because it removes the getpwnam call if the output of that call would not be used.

**Comment by robbat2** [comment]
@stappersg  bump, I still think this should get merged so getpwnam is not needed if configured correctly (would also give a way to not need NSS for this at all).

**Review by stappersg — APPROVED** [review]
Looks good to me.

**Comment by stappersg** [comment]
FWIW  in #165 is a link to 167   ( and now has this merge request also a linik to #167)

**Pull request merged**
